# Use case configuration for Nothing Phone (1)

SectionVerb {
	EnableSequence [
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia2' 1"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 1"
	]

	DisableSequence [
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia2' 0"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker & Earpiece Playback"

	Value {
		PlaybackChannels 2
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones Playback"

	Include.wcdhpe.File "/codecs/wcd938x/HeadphoneEnableSeq.conf"
	Include.wcdhpd.File "/codecs/wcd938x/HeadphoneDisableSeq.conf"
	Include.rxmhpe.File "/codecs/qcom-lpass/rx-macro/HeadphoneEnableSeq.conf"
	Include.rxmhpd.File "/codecs/qcom-lpass/rx-macro/HeadphoneDisableSeq.conf"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},1"
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "HP Digital"
		JackControl "Headphone Jack"
		JackHWMute "Speaker"
	}
}

SectionDevice."Mic1" {
	Comment "Top Microphone"

	# WCD9385 DMIC4 is routed to TX SWR_INPUT8.
	EnableSequence [
		cset "name='TX DEC2 MUX' SWR_MIC"
		cset "name='TX SMIC MUX2' SWR_MIC8"
		cset "name='TX_AIF1_CAP Mixer DEC2' 1"
		cset "name='TX_DEC2 Volume' 84"
		cset "name='DMIC5_MIXER Switch' 1"
		cset "name='DMIC4 Switch' 1"
	]

	DisableSequence [
		cset "name='TX SMIC MUX2' ZERO"
		cset "name='TX_AIF1_CAP Mixer DEC2' 0"
		cset "name='DMIC5_MIXER Switch' 0"
		cset "name='DMIC4 Switch' 0"
	]

	Value {
		CaptureChannels 1
		CapturePriority 200
		CapturePCM "hw:${CardId},2"
	}
}

SectionDevice."Mic2" {
	Comment "Headphone Microphone"

	EnableSequence [
		cset "name='TX DEC0 MUX' SWR_MIC"
		cset "name='TX SMIC MUX0' SWR_MIC1"
		cset "name='TX_AIF2_CAP Mixer DEC0' 1"
		cset "name='DEC0 MODE' ADC_DEFAULT"
		cset "name='TX_DEC0 Volume' 84"
		cset "name='ADC2_MIXER Switch' 1"
		cset "name='HDR12 MUX' NO_HDR12"
		cset "name='ADC2 MUX' INP2"
		cset "name='ADC2 Switch' 1"
		cset "name='TX1 MODE' ADC_LP"
	]

	DisableSequence [
		cset "name='TX SMIC MUX0' ZERO"
		cset "name='TX_AIF2_CAP Mixer DEC0' 0"
		cset "name='ADC2_MIXER Switch' 0"
		cset "name='ADC2 Switch' 0"
		cset "name='TX1 MODE' ADC_INVALID"
	]

	Value {
		CaptureChannels 1
		CapturePriority 150
		CapturePCM "hw:${CardId},2"
		CaptureMixerElem "ADC2"
	}
}

SectionDevice."Mic4" {
	Comment "Bottom Microphone"

	# WCD9385 DMIC6 is routed to TX SWR_INPUT10.
	EnableSequence [
		cset "name='TX DEC2 MUX' SWR_MIC"
		cset "name='TX SMIC MUX2' SWR_MIC10"
		cset "name='TX_AIF1_CAP Mixer DEC2' 1"
		cset "name='TX_DEC2 Volume' 84"
		cset "name='DMIC7_MIXER Switch' 1"
		cset "name='DMIC6 Switch' 1"
	]

	DisableSequence [
		cset "name='TX SMIC MUX2' ZERO"
		cset "name='TX_AIF1_CAP Mixer DEC2' 0"
		cset "name='DMIC7_MIXER Switch' 0"
		cset "name='DMIC6 Switch' 0"
	]

	Value {
		CaptureChannels 1
		CapturePriority 100
		CapturePCM "hw:${CardId},2"
	}
}

SectionDevice."Mic5" {
	Comment "Back Microphone"

	# WCD9385 DMIC7 is routed to TX SWR_INPUT11.
	EnableSequence [
		cset "name='TX DEC2 MUX' SWR_MIC"
		cset "name='TX SMIC MUX2' SWR_MIC11"
		cset "name='TX_AIF1_CAP Mixer DEC2' 1"
		cset "name='TX_DEC2 Volume' 84"
		cset "name='DMIC8_MIXER Switch' 1"
		cset "name='DMIC7 Switch' 1"
	]

	DisableSequence [
		cset "name='TX SMIC MUX2' ZERO"
		cset "name='TX_AIF1_CAP Mixer DEC2' 0"
		cset "name='DMIC8_MIXER Switch' 0"
		cset "name='DMIC7 Switch' 0"
	]

	Value {
		CaptureChannels 1
		CapturePriority 50
		CapturePCM "hw:${CardId},2"
	}
}
