# Use case configuration for Nothing Phone (1)

Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/sm8250/Nothing-Phone-1/HiFi.conf"
	Comment "HiFi quality Music."
}

BootSequence [
	cset "name='HPHL Volume' 20"
	cset "name='HPHR Volume' 20"
	cset "name='ADC2 Volume' 12"
]

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
Include.wcd-init.File "/codecs/wcd938x/init.conf"
Include.rxm-init.File "/codecs/qcom-lpass/rx-macro/init.conf"
